# Written by Mutlu Polatcan
# 17.12.2019
# --------------------------
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: airflow
    unit: database
spec:
  selector:
    app: airflow
    unit: database
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None