# Written by Mutlu Polatcan
# 17.12.2019
# --------------------------
apiVersion: v1
kind: Service
metadata:
  name: airflow-master
  labels:
    app: airflow
    unit: master
spec:
  selector:
    app: airflow
    unit: master
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort