# Written by Mutlu Polatcan
# 17.12.2019
# --------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow
    unit: webserver
spec:
  selector:
    matchLabels:
      app: airflow
      unit: webserver
  template:
    metadata:
      name: airflow-webserver
      labels:
        app: airflow
        unit: webserver
    spec:
      restartPolicy: Always
      containers:
        - name: airflow-webserver
          image: mpolatcan/airflow:1.10.6-python3.6
          imagePullPolicy: Always
          env:
            - name: AIRFLOW_DAEMONS
              value: |
                webserver
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secret
          ports:
            - containerPort: 8080 # Airflow UI Port