# Written by Mutlu Polatcan
# 17.12.2019
# --------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  labels:
    app: airflow
    unit: database
data:
  POSTGRES_USER: "airflow"
  POSTGRES_PASSWORD: "airflow"