# Written by Mutlu Polatcan
# 15.01.2020
# -------------------------
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow
  labels:
    app: airflow
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - list
      - get
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
      - get