# Written by Mutlu Polatcan
# 17.12.2019
# --------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-master
  labels:
    app: airflow
    unit: master
spec:
  selector:
    matchLabels:
      app: airflow
      unit: master
  template:
    metadata:
      name: airflow-master
      labels:
        app: airflow
        unit: master
    spec:
      restartPolicy: Always
      containers:
        - name: airflow-master
          image: mpolatcan/airflow:1.10.6-python3.6
          imagePullPolicy: Always
          env:
            - name: AIRFLOW_DAEMONS
              value: |
                scheduler
                webserver
                flower
          envFrom:
            - configMapRef:
                name: airflow
          ports:
            - containerPort: 8080 # Airflow UI Port
            - containerPort: 5555 # Celery Flower UI port