apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow
  labels:
    app: airflow
data:
  CORE_EXECUTOR: "CeleryExecutor"
  AIRFLOW_DATABASE_TYPE: "postgresql"
  AIRFLOW_DATABASE_HOST: "postgres"
  AIRFLOW_DATABASE_USER: "airflow"
  AIRFLOW_DATABASE_PASSWORD: "airflow"
  AIRFLOW_BROKER_TYPE: "redis"
  AIRFLOW_BROKER_HOST: "redis"
  AIRFLOW_BROKER_RESULT_BACKEND_TYPE: "postgresql"
  AIRFLOW_BROKER_RESULT_BACKEND_HOST: "postgres"
  AIRFLOW_BROKER_RESULT_BACKEND_USER: "airflow"
  AIRFLOW_BROKER_RESULT_BACKEND_PASSWORD: "airflow"
  WEBSERVER_AUTHENTICATE: "True"
  WEBSERVER_AUTH_BACKEND: "airflow.contrib.auth.backends.password_auth"
  WEBSERVER_RBAC: "True"