version: "3.6"
services:
  airflow-master:
    image: mpolatcan/airflow:1.10.6-python3.6
    container_name: airflow-master
    environment:
      CORE_EXECUTOR: CeleryExecutor
      CORE_SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres:5432/airflow
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow
      AIRFLOW_DAEMONS: |
        scheduler
        webserver
        flower
    ports:
      - 8080:8080
      - 5555:5555
    depends_on:
      - postgres
      - redis

  airflow-worker:
    image: mpolatcan/airflow:1.10.6-python3.6
    environment:
      CORE_EXECUTOR: CeleryExecutor
      CORE_SQL_ALCHEMY_CONN: postgresql://airflow:airflow@postgres:5432/airflow
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: db+postgresql://airflow:airflow@postgres:5432/airflow
      AIRFLOW_DAEMONS: |
        worker
    depends_on:
      - postgres
      - redis
      - airflow-master

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow

  redis:
    image: redis
    container_name: redis
    hostname: redis