base_dockerfile_template: |
  FROM python:3.6

  MAINTAINER Mutlu Polatcan <mutlupolatcan@gmail.com>

  ENV AIRFLOW_HOME="/airflow"
  ENV AIRFLOW_CONF_DIR="${{AIRFLOW_HOME}}" \
      AIRFLOW_DAEMONS="NULL" \
  {env_vars}

  WORKDIR ${{AIRFLOW_HOME}}

  ADD entrypoint.sh config_loader.sh ./

  RUN apt-get update && \
      apt-get -y install --no-install-recommends gcc g++ default-libmysqlclient-dev libkrb5-dev libsasl2-dev && \
      rm -rf /var/lib/apt/lists/* && \
      pip3 install "pymssql<3.0" && \
      pip3 install apache-airflow[all] && \
      chmod +x config_loader.sh entrypoint.sh

  ENTRYPOINT ["./entrypoint.sh"]

config_loader_sh_template: |
  #!/usr/bin/env bash

  function load_config() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "$1 = $2\n" >> "${{AIRFLOW_CONF_DIR}}/$3"
      fi
  }}

  function load_config_with_opt() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "$1 = $3\n" >> "${{AIRFLOW_CONF_DIR}}/$5"
      else
          printf "$1 = $4\n" >> "${{AIRFLOW_CONF_DIR}}/$5"
      fi
  }}

  {load_fn_calls}

config_files:
  - path: airflow_configs/airflow-cfg.yml
    filename: airflow.cfg

output_dir: ../../setup