apiVersion: v1
kind: PersistentVolume
metadata:
  name: airlfow-nfs-pv-rw
  labels:
    app: airflow
    storage: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /airflow-nfs
    server: 10.128.0.25
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-nfs-pvc-rw
  labels:
    app: airflow
spec:
  selector:
    matchLabels:
      storage: nfs
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # this is only arbitrary number, not real capacity of NFS storage