apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: airflow
    unit: broker
spec:
  selector:
    app: airflow
    unit: broker
  ports:
    - port: 6379
      targetPort: 6379
  clusterIP: None