# Written by Mutlu Polatcan
# 17.12.2019
# --------------------------
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  labels:
    app: airflow
stringData:
  AIRFLOW_INITIAL_USERS: |
    mpolatcan|12345|mutlupolatcan@gmail.com|Mutlu|Polatcan|Admin