# Written by Mutlu Polatcan
# 17.12.2019
# --------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  labels:
    app: airflow
data:
  CORE_EXECUTOR: "CeleryExecutor"
  AIRFLOW_DATABASE_TYPE: "postgresql"
  AIRFLOW_DATABASE_HOST: "postgres"
  AIRFLOW_DATABASE_USER: "airflow"
  AIRFLOW_DATABASE_PASSWORD: "airflow"
  AIRFLOW_BROKER_TYPE: "redis"
  AIRFLOW_BROKER_HOST: "redis"
  AIRFLOW_BROKER_RESULT_BACKEND_TYPE: "postgresql"
  AIRFLOW_BROKER_RESULT_BACKEND_HOST: "postgres"
  AIRFLOW_BROKER_RESULT_BACKEND_USER: "airflow"
  AIRFLOW_BROKER_RESULT_BACKEND_PASSWORD: "airflow"
  AIRFLOW_WEBSERVER_AUTH_BACKEND_TYPE: "password"
  WEBSERVER_AUTHENTICATE: "True"
  WEBSERVER_RBAC: "True"