# Written by Mutlu Polatcan
# 12.11.2019
# ------------------------------
version: "3.6"
services:
  airflow-scheduler:
    image: mpolatcan/airflow:1.10.6-python3.6
    container_name: airflow-scheduler
    environment:
      CORE_EXECUTOR: "CeleryExecutor"
      CORE_SQL_ALCHEMY_CONN: "postgresql://airflow:airflow@postgres:5432/airflow"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "db+postgresql://airflow:airflow@postgres:5432/airflow"
      AIRFLOW_DAEMONS: |
        scheduler
    volumes:
      - ./dags:/home/airflow/airflow/dags

  airflow-worker:
    image: mpolatcan/airflow:1.10.6-python3.6
    environment:
      CORE_EXECUTOR: "CeleryExecutor"
      CORE_SQL_ALCHEMY_CONN: "postgresql://airflow:airflow@postgres:5432/airflow"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "db+postgresql://airflow:airflow@postgres:5432/airflow"
      AIRFLOW_DAEMONS: |
        worker
    volumes:
      - ./dags:/home/airflow/airflow/dags

  airflow-webserver:
    image: mpolatcan/airflow:1.10.6-python3.6
    container_name: airflow-webserver
    environment:
      CORE_SQL_ALCHEMY_CONN: "postgresql://airflow:airflow@postgres:5432/airflow"
      WEBSERVER_AUTHENTICATE: "True"
      WEBSERVER_AUTH_BACKEND: "airflow.contrib.auth.backends.password_auth"
      AIRFLOW_DAEMONS: |
        webserver
    ports:
      - 8080:8080
    volumes:
      - ./dags:/home/airflow/airflow/dags

  celery-flower:
    image: mpolatcan/airflow:1.10.6-python3.6
    container_name: celery-flower
    environment:
      CORE_SQL_ALCHEMY_CONN: "postgresql://airflow:airflow@postgres:5432/airflow"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "db+postgresql://airflow:airflow@postgres:5432/airflow"
      AIRFLOW_DAEMONS: |
        flower
    ports:
      - 5555:5555
    volumes:
      - ./dags:/home/airflow/airflow/dags

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow

  redis:
    image: redis
    container_name: redis
    hostname: redis